services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: rootpassword  # Ensure you set this properly
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  django:
    entrypoint: ["bash", "-e", "/app/entrypoint.sh"]
    build: .
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "3", "cirtwebsite.wsgi:application"]
    volumes:
      - ./main/static:/app/static  # Mount static files to be accessible

volumes:
  mysql_data:
  static_volume:
